services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: Barusu123
     MYSQL_DATABASE: buku
    ports:
     - "3306:3306"

  app:
     build: .
     container_name: golang_app
     restart: always
     depends_on:
     - db
     ports:
     - "8080:8080"
     environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Barusu123
      DB_NAME:  buku

